// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface LauncherConfig {
    "linuxPatchComplete": boolean;
    "mangoHud": boolean;
    "fsr": boolean;
    "shaderCache": boolean;
    "hdr": boolean;
    "steamFix": boolean;
    "fpsLimit": string;
    "wineDllOverrides": string;
    "grafikMod": string;
    "fsrLvl": string;
}
