// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as utils$0 from "./src-wails/utils/models.js";

export function AutoIntegrateAppImage(): $CancellablePromise<void> {
    return $Call.ByID(2053624557);
}

export function BrowserOpenURL(url: string): $CancellablePromise<void> {
    return $Call.ByID(3458650668, url);
}

export function CheckCSFilesExist(): $CancellablePromise<boolean> {
    return $Call.ByID(1283171363);
}

export function FirstInstall(): $CancellablePromise<void> {
    return $Call.ByID(1213511276);
}

export function GetFirstInstallStatus(): $CancellablePromise<boolean> {
    return $Call.ByID(3403663732);
}

export function GetGameSettings(): $CancellablePromise<utils$0.LauncherConfig> {
    return $Call.ByID(728458824);
}

export function GetLauncherVersion(): $CancellablePromise<string> {
    return $Call.ByID(3151259337);
}

export function GetLocalVersion(): $CancellablePromise<string> {
    return $Call.ByID(2760347666);
}

export function GetRemoteVersion(): $CancellablePromise<string> {
    return $Call.ByID(488889167);
}

export function InstallGame(installerPath: string, installPath: string, oldMo2Path: string): $CancellablePromise<void> {
    return $Call.ByID(1203935082, installerPath, installPath, oldMo2Path);
}

export function IntegrateAppImageAndRelaunch(): $CancellablePromise<void> {
    return $Call.ByID(213760751);
}

export function IsPathExist(): $CancellablePromise<boolean> {
    return $Call.ByID(2236718721);
}

export function LoadPatches(): $CancellablePromise<string> {
    return $Call.ByID(2357717753);
}

export function Minimize(): $CancellablePromise<void> {
    return $Call.ByID(3000005589);
}

export function OpenExplorer(): $CancellablePromise<void> {
    return $Call.ByID(155793926);
}

export function OpenMO2(): $CancellablePromise<void> {
    return $Call.ByID(1307996457);
}

export function OpenProtonTrics(): $CancellablePromise<void> {
    return $Call.ByID(466718288);
}

export function Quit(): $CancellablePromise<void> {
    return $Call.ByID(3181047470);
}

export function RecoverComponent(key: string, force: boolean): $CancellablePromise<void> {
    return $Call.ByID(1233096830, key, force);
}

export function RunCommand(command: string, args: string[] | null): $CancellablePromise<string> {
    return $Call.ByID(1466765683, command, args);
}

export function SaveGlobalPath(mo2ExePath: string): $CancellablePromise<void> {
    return $Call.ByID(798309440, mo2ExePath);
}

/**
 * SelectDirectory открывает системное окно выбора папки
 */
export function SelectDirectory(): $CancellablePromise<string> {
    return $Call.ByID(1735672136);
}

/**
 * SelectFile открывает системное окно выбора файла
 */
export function SelectFile(): $CancellablePromise<string> {
    return $Call.ByID(2427571203);
}

/**
 * ShowMessageDialog показывает простое информационное окно
 */
export function ShowMessageDialog(title: string, message: string): $CancellablePromise<void> {
    return $Call.ByID(865005007, title, message);
}

export function StartGame(): $CancellablePromise<void> {
    return $Call.ByID(3309891005);
}

export function Update(): $CancellablePromise<void> {
    return $Call.ByID(4141298428);
}

/**
 * UpdateSetting сохраняет измененную настройку
 */
export function UpdateSetting(key: string, value: any): $CancellablePromise<void> {
    return $Call.ByID(3401798920, key, value);
}
