
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T extends DefineComponent> = T & DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>>
interface _GlobalComponents {
      'Button': typeof import("../components/Button.vue")['default']
    'CircleButton': typeof import("../components/CircleButton.vue")['default']
    'DirErrorMessage': typeof import("../components/DirErrorMessage.vue")['default']
    'DownloadingMessage': typeof import("../components/DownloadingMessage.vue")['default']
    'DropdownButton': typeof import("../components/DropdownButton.vue")['default']
    'GoogleDriveDirError': typeof import("../components/GoogleDriveDirError.vue")['default']
    'LauncherUpdatingMessage': typeof import("../components/LauncherUpdatingMessage.vue")['default']
    'ModComponent': typeof import("../components/ModComponent.vue")['default']
    'NetworkErrorMessage': typeof import("../components/NetworkErrorMessage.vue")['default']
    'PatchComponent': typeof import("../components/PatchComponent.vue")['default']
    'RemoteErrorMessage': typeof import("../components/RemoteErrorMessage.vue")['default']
    'SettingsModal': typeof import("../components/SettingsModal.vue")['default']
    'UnpackingMessage': typeof import("../components/UnpackingMessage.vue")['default']
    'UpdateAvailableMessage': typeof import("../components/UpdateAvailableMessage.vue")['default']
    'UpdateConfirmationMessage': typeof import("../components/UpdateConfirmationMessage.vue")['default']
    'UpdatingMessage': typeof import("../components/UpdatingMessage.vue")['default']
    'BaseBox': typeof import("../components/base/Box.vue")['default']
    'BaseMessageBox': typeof import("../components/base/MessageBox.vue")['default']
    'IconsBoosty': typeof import("../components/icons/Boosty.vue")['default']
    'IconsClock': typeof import("../components/icons/Clock.vue")['default']
    'IconsCog': typeof import("../components/icons/Cog.vue")['default']
    'IconsDiscord': typeof import("../components/icons/Discord.vue")['default']
    'IconsDownload': typeof import("../components/icons/Download.vue")['default']
    'IconsExpand': typeof import("../components/icons/Expand.vue")['default']
    'IconsFolder': typeof import("../components/icons/Folder.vue")['default']
    'IconsFolderSmallStroke': typeof import("../components/icons/FolderSmallStroke.vue")['default']
    'IconsGamepad': typeof import("../components/icons/Gamepad.vue")['default']
    'IconsMO2': typeof import("../components/icons/MO2.vue")['default']
    'IconsMinus': typeof import("../components/icons/Minus.vue")['default']
    'IconsOpenBook': typeof import("../components/icons/OpenBook.vue")['default']
    'IconsPackage': typeof import("../components/icons/Package.vue")['default']
    'IconsTelegram': typeof import("../components/icons/Telegram.vue")['default']
    'IconsUser': typeof import("../components/icons/User.vue")['default']
    'IconsVk': typeof import("../components/icons/Vk.vue")['default']
    'IconsX': typeof import("../components/icons/X.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'NuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'NuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'NuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'NuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
      'LazyButton': typeof import("../components/Button.vue")['default']
    'LazyCircleButton': typeof import("../components/CircleButton.vue")['default']
    'LazyDirErrorMessage': typeof import("../components/DirErrorMessage.vue")['default']
    'LazyDownloadingMessage': typeof import("../components/DownloadingMessage.vue")['default']
    'LazyDropdownButton': typeof import("../components/DropdownButton.vue")['default']
    'LazyGoogleDriveDirError': typeof import("../components/GoogleDriveDirError.vue")['default']
    'LazyLauncherUpdatingMessage': typeof import("../components/LauncherUpdatingMessage.vue")['default']
    'LazyModComponent': typeof import("../components/ModComponent.vue")['default']
    'LazyNetworkErrorMessage': typeof import("../components/NetworkErrorMessage.vue")['default']
    'LazyPatchComponent': typeof import("../components/PatchComponent.vue")['default']
    'LazyRemoteErrorMessage': typeof import("../components/RemoteErrorMessage.vue")['default']
    'LazySettingsModal': typeof import("../components/SettingsModal.vue")['default']
    'LazyUnpackingMessage': typeof import("../components/UnpackingMessage.vue")['default']
    'LazyUpdateAvailableMessage': typeof import("../components/UpdateAvailableMessage.vue")['default']
    'LazyUpdateConfirmationMessage': typeof import("../components/UpdateConfirmationMessage.vue")['default']
    'LazyUpdatingMessage': typeof import("../components/UpdatingMessage.vue")['default']
    'LazyBaseBox': typeof import("../components/base/Box.vue")['default']
    'LazyBaseMessageBox': typeof import("../components/base/MessageBox.vue")['default']
    'LazyIconsBoosty': typeof import("../components/icons/Boosty.vue")['default']
    'LazyIconsClock': typeof import("../components/icons/Clock.vue")['default']
    'LazyIconsCog': typeof import("../components/icons/Cog.vue")['default']
    'LazyIconsDiscord': typeof import("../components/icons/Discord.vue")['default']
    'LazyIconsDownload': typeof import("../components/icons/Download.vue")['default']
    'LazyIconsExpand': typeof import("../components/icons/Expand.vue")['default']
    'LazyIconsFolder': typeof import("../components/icons/Folder.vue")['default']
    'LazyIconsFolderSmallStroke': typeof import("../components/icons/FolderSmallStroke.vue")['default']
    'LazyIconsGamepad': typeof import("../components/icons/Gamepad.vue")['default']
    'LazyIconsMO2': typeof import("../components/icons/MO2.vue")['default']
    'LazyIconsMinus': typeof import("../components/icons/Minus.vue")['default']
    'LazyIconsOpenBook': typeof import("../components/icons/OpenBook.vue")['default']
    'LazyIconsPackage': typeof import("../components/icons/Package.vue")['default']
    'LazyIconsTelegram': typeof import("../components/icons/Telegram.vue")['default']
    'LazyIconsUser': typeof import("../components/icons/User.vue")['default']
    'LazyIconsVk': typeof import("../components/icons/Vk.vue")['default']
    'LazyIconsX': typeof import("../components/icons/X.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'LazyNuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'LazyNuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'LazyNuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'LazyNuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const Button: typeof import("../components/Button.vue")['default']
export const CircleButton: typeof import("../components/CircleButton.vue")['default']
export const DirErrorMessage: typeof import("../components/DirErrorMessage.vue")['default']
export const DownloadingMessage: typeof import("../components/DownloadingMessage.vue")['default']
export const DropdownButton: typeof import("../components/DropdownButton.vue")['default']
export const GoogleDriveDirError: typeof import("../components/GoogleDriveDirError.vue")['default']
export const LauncherUpdatingMessage: typeof import("../components/LauncherUpdatingMessage.vue")['default']
export const ModComponent: typeof import("../components/ModComponent.vue")['default']
export const NetworkErrorMessage: typeof import("../components/NetworkErrorMessage.vue")['default']
export const PatchComponent: typeof import("../components/PatchComponent.vue")['default']
export const RemoteErrorMessage: typeof import("../components/RemoteErrorMessage.vue")['default']
export const SettingsModal: typeof import("../components/SettingsModal.vue")['default']
export const UnpackingMessage: typeof import("../components/UnpackingMessage.vue")['default']
export const UpdateAvailableMessage: typeof import("../components/UpdateAvailableMessage.vue")['default']
export const UpdateConfirmationMessage: typeof import("../components/UpdateConfirmationMessage.vue")['default']
export const UpdatingMessage: typeof import("../components/UpdatingMessage.vue")['default']
export const BaseBox: typeof import("../components/base/Box.vue")['default']
export const BaseMessageBox: typeof import("../components/base/MessageBox.vue")['default']
export const IconsBoosty: typeof import("../components/icons/Boosty.vue")['default']
export const IconsClock: typeof import("../components/icons/Clock.vue")['default']
export const IconsCog: typeof import("../components/icons/Cog.vue")['default']
export const IconsDiscord: typeof import("../components/icons/Discord.vue")['default']
export const IconsDownload: typeof import("../components/icons/Download.vue")['default']
export const IconsExpand: typeof import("../components/icons/Expand.vue")['default']
export const IconsFolder: typeof import("../components/icons/Folder.vue")['default']
export const IconsFolderSmallStroke: typeof import("../components/icons/FolderSmallStroke.vue")['default']
export const IconsGamepad: typeof import("../components/icons/Gamepad.vue")['default']
export const IconsMO2: typeof import("../components/icons/MO2.vue")['default']
export const IconsMinus: typeof import("../components/icons/Minus.vue")['default']
export const IconsOpenBook: typeof import("../components/icons/OpenBook.vue")['default']
export const IconsPackage: typeof import("../components/icons/Package.vue")['default']
export const IconsTelegram: typeof import("../components/icons/Telegram.vue")['default']
export const IconsUser: typeof import("../components/icons/User.vue")['default']
export const IconsVk: typeof import("../components/icons/Vk.vue")['default']
export const IconsX: typeof import("../components/icons/X.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyButton: typeof import("../components/Button.vue")['default']
export const LazyCircleButton: typeof import("../components/CircleButton.vue")['default']
export const LazyDirErrorMessage: typeof import("../components/DirErrorMessage.vue")['default']
export const LazyDownloadingMessage: typeof import("../components/DownloadingMessage.vue")['default']
export const LazyDropdownButton: typeof import("../components/DropdownButton.vue")['default']
export const LazyGoogleDriveDirError: typeof import("../components/GoogleDriveDirError.vue")['default']
export const LazyLauncherUpdatingMessage: typeof import("../components/LauncherUpdatingMessage.vue")['default']
export const LazyModComponent: typeof import("../components/ModComponent.vue")['default']
export const LazyNetworkErrorMessage: typeof import("../components/NetworkErrorMessage.vue")['default']
export const LazyPatchComponent: typeof import("../components/PatchComponent.vue")['default']
export const LazyRemoteErrorMessage: typeof import("../components/RemoteErrorMessage.vue")['default']
export const LazySettingsModal: typeof import("../components/SettingsModal.vue")['default']
export const LazyUnpackingMessage: typeof import("../components/UnpackingMessage.vue")['default']
export const LazyUpdateAvailableMessage: typeof import("../components/UpdateAvailableMessage.vue")['default']
export const LazyUpdateConfirmationMessage: typeof import("../components/UpdateConfirmationMessage.vue")['default']
export const LazyUpdatingMessage: typeof import("../components/UpdatingMessage.vue")['default']
export const LazyBaseBox: typeof import("../components/base/Box.vue")['default']
export const LazyBaseMessageBox: typeof import("../components/base/MessageBox.vue")['default']
export const LazyIconsBoosty: typeof import("../components/icons/Boosty.vue")['default']
export const LazyIconsClock: typeof import("../components/icons/Clock.vue")['default']
export const LazyIconsCog: typeof import("../components/icons/Cog.vue")['default']
export const LazyIconsDiscord: typeof import("../components/icons/Discord.vue")['default']
export const LazyIconsDownload: typeof import("../components/icons/Download.vue")['default']
export const LazyIconsExpand: typeof import("../components/icons/Expand.vue")['default']
export const LazyIconsFolder: typeof import("../components/icons/Folder.vue")['default']
export const LazyIconsFolderSmallStroke: typeof import("../components/icons/FolderSmallStroke.vue")['default']
export const LazyIconsGamepad: typeof import("../components/icons/Gamepad.vue")['default']
export const LazyIconsMO2: typeof import("../components/icons/MO2.vue")['default']
export const LazyIconsMinus: typeof import("../components/icons/Minus.vue")['default']
export const LazyIconsOpenBook: typeof import("../components/icons/OpenBook.vue")['default']
export const LazyIconsPackage: typeof import("../components/icons/Package.vue")['default']
export const LazyIconsTelegram: typeof import("../components/icons/Telegram.vue")['default']
export const LazyIconsUser: typeof import("../components/icons/User.vue")['default']
export const LazyIconsVk: typeof import("../components/icons/Vk.vue")['default']
export const LazyIconsX: typeof import("../components/icons/X.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const LazyNuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const LazyNuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const LazyNuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyNuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>

export const componentNames: string[]
