// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FirstInstall() {
  return window['go']['main']['App']['FirstInstall']();
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetFirstInstallStatus() {
  return window['go']['main']['App']['GetFirstInstallStatus']();
}

export function GetFramerateLimit() {
  return window['go']['main']['App']['GetFramerateLimit']();
}

export function GetHomeDir() {
  return window['go']['main']['App']['GetHomeDir']();
}

export function GetLauncherVersion() {
  return window['go']['main']['App']['GetLauncherVersion']();
}

export function GetLocalVersion() {
  return window['go']['main']['App']['GetLocalVersion']();
}

export function GetRemoteVersion() {
  return window['go']['main']['App']['GetRemoteVersion']();
}

export function GetVoiceLocale() {
  return window['go']['main']['App']['GetVoiceLocale']();
}

export function InstallGame(arg1, arg2) {
  return window['go']['main']['App']['InstallGame'](arg1, arg2);
}

export function IsPathExist() {
  return window['go']['main']['App']['IsPathExist']();
}

export function LoadPatches() {
  return window['go']['main']['App']['LoadPatches']();
}

export function OpenBrowser(arg1) {
  return window['go']['main']['App']['OpenBrowser'](arg1);
}

export function OpenExplorer() {
  return window['go']['main']['App']['OpenExplorer']();
}

export function OpenMO2() {
  return window['go']['main']['App']['OpenMO2']();
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function RunCommand(arg1, arg2) {
  return window['go']['main']['App']['RunCommand'](arg1, arg2);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}

export function ShowMessageDialog(arg1, arg2) {
  return window['go']['main']['App']['ShowMessageDialog'](arg1, arg2);
}

export function StartGame() {
  return window['go']['main']['App']['StartGame']();
}

export function StartNewLauncher() {
  return window['go']['main']['App']['StartNewLauncher']();
}

export function Update() {
  return window['go']['main']['App']['Update']();
}

export function UpdateGameSettings(arg1, arg2) {
  return window['go']['main']['App']['UpdateGameSettings'](arg1, arg2);
}

export function UpdateLauncher(arg1) {
  return window['go']['main']['App']['UpdateLauncher'](arg1);
}

export function WriteFile(arg1, arg2) {
  return window['go']['main']['App']['WriteFile'](arg1, arg2);
}
