// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {core} from '../models';

export function BrowserOpenURL(arg1:string):Promise<void>;

export function FirstInstall():Promise<void>;

export function GetAppVersion():Promise<string>;

export function GetFirstInstallStatus():Promise<boolean>;

export function GetFramerateLimit():Promise<number>;

export function GetGameSettings():Promise<core.LauncherConfig>;

export function GetHomeDir():Promise<string>;

export function GetLauncherVersion():Promise<string>;

export function GetLocalVersion():Promise<string>;

export function GetRemoteVersion():Promise<string>;

export function GetVoiceLocale():Promise<string>;

export function InstallGame(arg1:string,arg2:string):Promise<void>;

export function IsPathExist():Promise<boolean>;

export function LoadPatches():Promise<string>;

export function OpenExplorer():Promise<void>;

export function OpenMO2():Promise<void>;

export function ReadFile(arg1:string):Promise<string>;

export function RunCommand(arg1:string,arg2:Array<string>):Promise<string>;

export function SelectDirectory():Promise<string>;

export function SelectFile():Promise<string>;

export function ShowMessageDialog(arg1:string,arg2:string):Promise<void>;

export function StartGame():Promise<void>;

export function StartNewLauncher():Promise<void>;

export function Update():Promise<void>;

export function UpdateGameSettings(arg1:number,arg2:string):Promise<void>;

export function UpdateLauncher(arg1:string):Promise<void>;

export function UpdateSetting(arg1:string,arg2:any):Promise<void>;

export function WriteFile(arg1:string,arg2:string):Promise<void>;
